export default {
  "login": "sunnepazzy123",
  "id": 39708757,
  "node_id": "MDQ6VXNlcjM5NzA4NzU3",
  "avatar_url": "https://avatars0.githubusercontent.com/u/39708757?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/sunnepazzy123",
  "html_url": "https://github.com/sunnepazzy123",
  "followers_url": "https://api.github.com/users/sunnepazzy123/followers",
  "following_url": "https://api.github.com/users/sunnepazzy123/following{/other_user}",
  "gists_url": "https://api.github.com/users/sunnepazzy123/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/sunnepazzy123/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/sunnepazzy123/subscriptions",
  "organizations_url": "https://api.github.com/users/sunnepazzy123/orgs",
  "repos_url": "https://api.github.com/users/sunnepazzy123/repos",
  "events_url": "https://api.github.com/users/sunnepazzy123/events{/privacy}",
  "received_events_url": "https://api.github.com/users/sunnepazzy123/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Sunday Odibo",
  "company": "WireDevTeam",
  "blog": "",
  "location": "Nigeria",
  "email": null,
  "hireable": null,
  "bio": "I am a JavaScript Developer, Php and Python",
  "twitter_username": null,
  "public_repos": 31,
  "public_gists": 0,
  "followers": 2,
  "following": 23,
  "created_at": "2018-05-28T18:09:31Z",
  "updated_at": "2020-07-28T02:27:35Z"
};