export default [
  {
    "login": "victorichmedia",
    "id": 59113944,
    "node_id": "MDQ6VXNlcjU5MTEzOTQ0",
    "avatar_url": "https://avatars2.githubusercontent.com/u/59113944?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/victorichmedia",
    "html_url": "https://github.com/victorichmedia",
    "followers_url": "https://api.github.com/users/victorichmedia/followers",
    "following_url": "https://api.github.com/users/victorichmedia/following{/other_user}",
    "gists_url": "https://api.github.com/users/victorichmedia/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/victorichmedia/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/victorichmedia/subscriptions",
    "organizations_url": "https://api.github.com/users/victorichmedia/orgs",
    "repos_url": "https://api.github.com/users/victorichmedia/repos",
    "events_url": "https://api.github.com/users/victorichmedia/events{/privacy}",
    "received_events_url": "https://api.github.com/users/victorichmedia/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "esmelyn067",
    "id": 58703950,
    "node_id": "MDQ6VXNlcjU4NzAzOTUw",
    "avatar_url": "https://avatars3.githubusercontent.com/u/58703950?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/esmelyn067",
    "html_url": "https://github.com/esmelyn067",
    "followers_url": "https://api.github.com/users/esmelyn067/followers",
    "following_url": "https://api.github.com/users/esmelyn067/following{/other_user}",
    "gists_url": "https://api.github.com/users/esmelyn067/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/esmelyn067/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/esmelyn067/subscriptions",
    "organizations_url": "https://api.github.com/users/esmelyn067/orgs",
    "repos_url": "https://api.github.com/users/esmelyn067/repos",
    "events_url": "https://api.github.com/users/esmelyn067/events{/privacy}",
    "received_events_url": "https://api.github.com/users/esmelyn067/received_events",
    "type": "User",
    "site_admin": false
  }
]